name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest   
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: python -m pip install pyinstaller
      - run: python -m pip install -r requirements.txt -r requirements.build.txt
      - run: pyinstaller --clean -y --dist ./dist/windows --log-level DEBUG entry_point.spec      
      # Target folder will be the latest commit hash
      - run: python upload_to_r2 --bucket_name ${{ secrets.AWS_BUCKET }} --dist_folder ./dist/windows --target_folder ${{ github.sha }}