name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: python -m pip install pyinstaller
      - run: python -m pip install requirements.txt
      - run: pyinstaller --clean -y --dist ./dist/windows --log-level DEBUG 
      - uses: actions/upload-artifact@v4
        with:
          name: entrypoint-exe
          path: dist/windows



